package com.arman.csb.theme.model.impl;

import com.arman.csb.theme.model.ContentHolder;
import com.arman.csb.theme.service.ContentHolderLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ContentHolder service. Represents a row in the &quot;CSB_ContentHolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentHolderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentHolderImpl
 * @see com.arman.csb.theme.model.ContentHolder
 * @generated
 */
public abstract class ContentHolderBaseImpl extends ContentHolderModelImpl
    implements ContentHolder {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a content holder model instance should use the {@link ContentHolder} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ContentHolderLocalServiceUtil.addContentHolder(this);
        } else {
            ContentHolderLocalServiceUtil.updateContentHolder(this);
        }
    }
}
