package com.arman.csb.theme.model.impl;

import com.arman.csb.theme.model.Template;
import com.arman.csb.theme.service.TemplateLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Template service. Represents a row in the &quot;CSB_Template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemplateImpl
 * @see com.arman.csb.theme.model.Template
 * @generated
 */
public abstract class TemplateBaseImpl extends TemplateModelImpl
    implements Template {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a template model instance should use the {@link Template} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TemplateLocalServiceUtil.addTemplate(this);
        } else {
            TemplateLocalServiceUtil.updateTemplate(this);
        }
    }
}
