package com.arman.csb.modules.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Payment service. Represents a row in the &quot;CSBModules_Payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.arman.csb.modules.model.impl.PaymentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.arman.csb.modules.model.impl.PaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Payment
 * @see com.arman.csb.modules.model.impl.PaymentImpl
 * @see com.arman.csb.modules.model.impl.PaymentModelImpl
 * @generated
 */
public interface PaymentModel extends BaseModel<Payment>, StagedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a payment model instance should use the {@link Payment} interface instead.
     */

    /**
     * Returns the primary key of this payment.
     *
     * @return the primary key of this payment
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this payment.
     *
     * @param primaryKey the primary key of this payment
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this payment.
     *
     * @return the uuid of this payment
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this payment.
     *
     * @param uuid the uuid of this payment
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the ID of this payment.
     *
     * @return the ID of this payment
     */
    public long getId();

    /**
     * Sets the ID of this payment.
     *
     * @param id the ID of this payment
     */
    public void setId(long id);

    /**
     * Returns the group ID of this payment.
     *
     * @return the group ID of this payment
     */
    public long getGroupId();

    /**
     * Sets the group ID of this payment.
     *
     * @param groupId the group ID of this payment
     */
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this payment.
     *
     * @return the company ID of this payment
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this payment.
     *
     * @param companyId the company ID of this payment
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this payment.
     *
     * @return the user ID of this payment
     */
    public long getUserId();

    /**
     * Sets the user ID of this payment.
     *
     * @param userId the user ID of this payment
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this payment.
     *
     * @return the user uuid of this payment
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this payment.
     *
     * @param userUuid the user uuid of this payment
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the create date of this payment.
     *
     * @return the create date of this payment
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this payment.
     *
     * @param createDate the create date of this payment
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this payment.
     *
     * @return the modified date of this payment
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this payment.
     *
     * @param modifiedDate the modified date of this payment
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the description of this payment.
     *
     * @return the description of this payment
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this payment.
     *
     * @param description the description of this payment
     */
    public void setDescription(String description);

    /**
     * Returns the card of this payment.
     *
     * @return the card of this payment
     */
    @AutoEscape
    public String getCard();

    /**
     * Sets the card of this payment.
     *
     * @param card the card of this payment
     */
    public void setCard(String card);

    /**
     * Returns the amount of this payment.
     *
     * @return the amount of this payment
     */
    public long getAmount();

    /**
     * Sets the amount of this payment.
     *
     * @param amount the amount of this payment
     */
    public void setAmount(long amount);

    /**
     * Returns the status of this payment.
     *
     * @return the status of this payment
     */
    public int getStatus();

    /**
     * Sets the status of this payment.
     *
     * @param status the status of this payment
     */
    public void setStatus(int status);

    /**
     * Returns the payment date of this payment.
     *
     * @return the payment date of this payment
     */
    public Date getPaymentDate();

    /**
     * Sets the payment date of this payment.
     *
     * @param paymentDate the payment date of this payment
     */
    public void setPaymentDate(Date paymentDate);

    /**
     * Returns the customer ID of this payment.
     *
     * @return the customer ID of this payment
     */
    public long getCustomerId();

    /**
     * Sets the customer ID of this payment.
     *
     * @param customerId the customer ID of this payment
     */
    public void setCustomerId(long customerId);

    /**
     * Returns the factor ID of this payment.
     *
     * @return the factor ID of this payment
     */
    public long getFactorId();

    /**
     * Sets the factor ID of this payment.
     *
     * @param factorId the factor ID of this payment
     */
    public void setFactorId(long factorId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Payment payment);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Payment> toCacheModel();

    @Override
    public Payment toEscapedModel();

    @Override
    public Payment toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
