package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Customer;
import com.arman.csb.modules.model.CustomerModel;
import com.arman.csb.modules.model.CustomerSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Customer service. Represents a row in the &quot;CSBModules_Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.arman.csb.modules.model.CustomerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerImpl
 * @see com.arman.csb.modules.model.Customer
 * @see com.arman.csb.modules.model.CustomerModel
 * @generated
 */
@JSON(strict = true)
public class CustomerModelImpl extends BaseModelImpl<Customer>
    implements CustomerModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a customer model instance should use the {@link com.arman.csb.modules.model.Customer} interface instead.
     */
    public static final String TABLE_NAME = "CSBModules_Customer";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "id_", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "mobile", Types.VARCHAR },
            { "nationalCode", Types.VARCHAR },
            { "email", Types.VARCHAR },
            { "card", Types.VARCHAR },
            { "score", Types.INTEGER },
            { "status", Types.INTEGER },
            { "customerUserId", Types.BIGINT },
            { "mentorCustomerId", Types.BIGINT }
        };
    public static final String TABLE_SQL_CREATE = "create table CSBModules_Customer (uuid_ VARCHAR(75) null,id_ LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,mobile VARCHAR(75) null,nationalCode VARCHAR(75) null,email VARCHAR(75) null,card VARCHAR(75) null,score INTEGER,status INTEGER,customerUserId LONG,mentorCustomerId LONG)";
    public static final String TABLE_SQL_DROP = "drop table CSBModules_Customer";
    public static final String ORDER_BY_JPQL = " ORDER BY customer.id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY CSBModules_Customer.id_ ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.arman.csb.modules.model.Customer"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.arman.csb.modules.model.Customer"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.arman.csb.modules.model.Customer"),
            true);
    public static long COMPANYID_COLUMN_BITMASK = 1L;
    public static long GROUPID_COLUMN_BITMASK = 2L;
    public static long UUID_COLUMN_BITMASK = 4L;
    public static long ID_COLUMN_BITMASK = 8L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.arman.csb.modules.model.Customer"));
    private static ClassLoader _classLoader = Customer.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            Customer.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _id;
    private long _groupId;
    private long _originalGroupId;
    private boolean _setOriginalGroupId;
    private long _companyId;
    private long _originalCompanyId;
    private boolean _setOriginalCompanyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _mobile;
    private String _nationalCode;
    private String _email;
    private String _card;
    private int _score;
    private int _status;
    private long _customerUserId;
    private String _customerUserUuid;
    private long _mentorCustomerId;
    private long _columnBitmask;
    private Customer _escapedModel;

    public CustomerModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Customer toModel(CustomerSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Customer model = new CustomerImpl();

        model.setUuid(soapModel.getUuid());
        model.setId(soapModel.getId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setMobile(soapModel.getMobile());
        model.setNationalCode(soapModel.getNationalCode());
        model.setEmail(soapModel.getEmail());
        model.setCard(soapModel.getCard());
        model.setScore(soapModel.getScore());
        model.setStatus(soapModel.getStatus());
        model.setCustomerUserId(soapModel.getCustomerUserId());
        model.setMentorCustomerId(soapModel.getMentorCustomerId());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Customer> toModels(CustomerSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Customer> models = new ArrayList<Customer>(soapModels.length);

        for (CustomerSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Customer.class;
    }

    @Override
    public String getModelClassName() {
        return Customer.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("id", getId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("mobile", getMobile());
        attributes.put("nationalCode", getNationalCode());
        attributes.put("email", getEmail());
        attributes.put("card", getCard());
        attributes.put("score", getScore());
        attributes.put("status", getStatus());
        attributes.put("customerUserId", getCustomerUserId());
        attributes.put("mentorCustomerId", getMentorCustomerId());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long id = (Long) attributes.get("id");

        if (id != null) {
            setId(id);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String mobile = (String) attributes.get("mobile");

        if (mobile != null) {
            setMobile(mobile);
        }

        String nationalCode = (String) attributes.get("nationalCode");

        if (nationalCode != null) {
            setNationalCode(nationalCode);
        }

        String email = (String) attributes.get("email");

        if (email != null) {
            setEmail(email);
        }

        String card = (String) attributes.get("card");

        if (card != null) {
            setCard(card);
        }

        Integer score = (Integer) attributes.get("score");

        if (score != null) {
            setScore(score);
        }

        Integer status = (Integer) attributes.get("status");

        if (status != null) {
            setStatus(status);
        }

        Long customerUserId = (Long) attributes.get("customerUserId");

        if (customerUserId != null) {
            setCustomerUserId(customerUserId);
        }

        Long mentorCustomerId = (Long) attributes.get("mentorCustomerId");

        if (mentorCustomerId != null) {
            setMentorCustomerId(mentorCustomerId);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getId() {
        return _id;
    }

    @Override
    public void setId(long id) {
        _id = id;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _columnBitmask |= GROUPID_COLUMN_BITMASK;

        if (!_setOriginalGroupId) {
            _setOriginalGroupId = true;

            _originalGroupId = _groupId;
        }

        _groupId = groupId;
    }

    public long getOriginalGroupId() {
        return _originalGroupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _columnBitmask |= COMPANYID_COLUMN_BITMASK;

        if (!_setOriginalCompanyId) {
            _setOriginalCompanyId = true;

            _originalCompanyId = _companyId;
        }

        _companyId = companyId;
    }

    public long getOriginalCompanyId() {
        return _originalCompanyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getMobile() {
        if (_mobile == null) {
            return StringPool.BLANK;
        } else {
            return _mobile;
        }
    }

    @Override
    public void setMobile(String mobile) {
        _mobile = mobile;
    }

    @JSON
    @Override
    public String getNationalCode() {
        if (_nationalCode == null) {
            return StringPool.BLANK;
        } else {
            return _nationalCode;
        }
    }

    @Override
    public void setNationalCode(String nationalCode) {
        _nationalCode = nationalCode;
    }

    @JSON
    @Override
    public String getEmail() {
        if (_email == null) {
            return StringPool.BLANK;
        } else {
            return _email;
        }
    }

    @Override
    public void setEmail(String email) {
        _email = email;
    }

    @JSON
    @Override
    public String getCard() {
        if (_card == null) {
            return StringPool.BLANK;
        } else {
            return _card;
        }
    }

    @Override
    public void setCard(String card) {
        _card = card;
    }

    @JSON
    @Override
    public int getScore() {
        return _score;
    }

    @Override
    public void setScore(int score) {
        _score = score;
    }

    @JSON
    @Override
    public int getStatus() {
        return _status;
    }

    @Override
    public void setStatus(int status) {
        _status = status;
    }

    @JSON
    @Override
    public long getCustomerUserId() {
        return _customerUserId;
    }

    @Override
    public void setCustomerUserId(long customerUserId) {
        _customerUserId = customerUserId;
    }

    @Override
    public String getCustomerUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getCustomerUserId(), "uuid",
            _customerUserUuid);
    }

    @Override
    public void setCustomerUserUuid(String customerUserUuid) {
        _customerUserUuid = customerUserUuid;
    }

    @JSON
    @Override
    public long getMentorCustomerId() {
        return _mentorCustomerId;
    }

    @Override
    public void setMentorCustomerId(long mentorCustomerId) {
        _mentorCustomerId = mentorCustomerId;
    }

    @Override
    public StagedModelType getStagedModelType() {
        return new StagedModelType(PortalUtil.getClassNameId(
                Customer.class.getName()));
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            Customer.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Customer toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Customer) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        CustomerImpl customerImpl = new CustomerImpl();

        customerImpl.setUuid(getUuid());
        customerImpl.setId(getId());
        customerImpl.setGroupId(getGroupId());
        customerImpl.setCompanyId(getCompanyId());
        customerImpl.setUserId(getUserId());
        customerImpl.setUserName(getUserName());
        customerImpl.setCreateDate(getCreateDate());
        customerImpl.setModifiedDate(getModifiedDate());
        customerImpl.setName(getName());
        customerImpl.setMobile(getMobile());
        customerImpl.setNationalCode(getNationalCode());
        customerImpl.setEmail(getEmail());
        customerImpl.setCard(getCard());
        customerImpl.setScore(getScore());
        customerImpl.setStatus(getStatus());
        customerImpl.setCustomerUserId(getCustomerUserId());
        customerImpl.setMentorCustomerId(getMentorCustomerId());

        customerImpl.resetOriginalValues();

        return customerImpl;
    }

    @Override
    public int compareTo(Customer customer) {
        long primaryKey = customer.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Customer)) {
            return false;
        }

        Customer customer = (Customer) obj;

        long primaryKey = customer.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        CustomerModelImpl customerModelImpl = this;

        customerModelImpl._originalUuid = customerModelImpl._uuid;

        customerModelImpl._originalGroupId = customerModelImpl._groupId;

        customerModelImpl._setOriginalGroupId = false;

        customerModelImpl._originalCompanyId = customerModelImpl._companyId;

        customerModelImpl._setOriginalCompanyId = false;

        customerModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Customer> toCacheModel() {
        CustomerCacheModel customerCacheModel = new CustomerCacheModel();

        customerCacheModel.uuid = getUuid();

        String uuid = customerCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            customerCacheModel.uuid = null;
        }

        customerCacheModel.id = getId();

        customerCacheModel.groupId = getGroupId();

        customerCacheModel.companyId = getCompanyId();

        customerCacheModel.userId = getUserId();

        customerCacheModel.userName = getUserName();

        String userName = customerCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            customerCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            customerCacheModel.createDate = createDate.getTime();
        } else {
            customerCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            customerCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            customerCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        customerCacheModel.name = getName();

        String name = customerCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            customerCacheModel.name = null;
        }

        customerCacheModel.mobile = getMobile();

        String mobile = customerCacheModel.mobile;

        if ((mobile != null) && (mobile.length() == 0)) {
            customerCacheModel.mobile = null;
        }

        customerCacheModel.nationalCode = getNationalCode();

        String nationalCode = customerCacheModel.nationalCode;

        if ((nationalCode != null) && (nationalCode.length() == 0)) {
            customerCacheModel.nationalCode = null;
        }

        customerCacheModel.email = getEmail();

        String email = customerCacheModel.email;

        if ((email != null) && (email.length() == 0)) {
            customerCacheModel.email = null;
        }

        customerCacheModel.card = getCard();

        String card = customerCacheModel.card;

        if ((card != null) && (card.length() == 0)) {
            customerCacheModel.card = null;
        }

        customerCacheModel.score = getScore();

        customerCacheModel.status = getStatus();

        customerCacheModel.customerUserId = getCustomerUserId();

        customerCacheModel.mentorCustomerId = getMentorCustomerId();

        return customerCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(35);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", id=");
        sb.append(getId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", mobile=");
        sb.append(getMobile());
        sb.append(", nationalCode=");
        sb.append(getNationalCode());
        sb.append(", email=");
        sb.append(getEmail());
        sb.append(", card=");
        sb.append(getCard());
        sb.append(", score=");
        sb.append(getScore());
        sb.append(", status=");
        sb.append(getStatus());
        sb.append(", customerUserId=");
        sb.append(getCustomerUserId());
        sb.append(", mentorCustomerId=");
        sb.append(getMentorCustomerId());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(55);

        sb.append("<model><model-name>");
        sb.append("com.arman.csb.modules.model.Customer");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>id</column-name><column-value><![CDATA[");
        sb.append(getId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>mobile</column-name><column-value><![CDATA[");
        sb.append(getMobile());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>nationalCode</column-name><column-value><![CDATA[");
        sb.append(getNationalCode());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>email</column-name><column-value><![CDATA[");
        sb.append(getEmail());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>card</column-name><column-value><![CDATA[");
        sb.append(getCard());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>score</column-name><column-value><![CDATA[");
        sb.append(getScore());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>status</column-name><column-value><![CDATA[");
        sb.append(getStatus());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>customerUserId</column-name><column-value><![CDATA[");
        sb.append(getCustomerUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>mentorCustomerId</column-name><column-value><![CDATA[");
        sb.append(getMentorCustomerId());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
