package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Instance;
import com.arman.csb.modules.service.InstanceLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Instance service. Represents a row in the &quot;CSBModules_Instance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstanceImpl
 * @see com.arman.csb.modules.model.Instance
 * @generated
 */
public abstract class InstanceBaseImpl extends InstanceModelImpl
    implements Instance {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a instance model instance should use the {@link Instance} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            InstanceLocalServiceUtil.addInstance(this);
        } else {
            InstanceLocalServiceUtil.updateInstance(this);
        }
    }
}
