package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Invoice;
import com.arman.csb.modules.service.InvoiceLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Invoice service. Represents a row in the &quot;CSBModules_Invoice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InvoiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvoiceImpl
 * @see com.arman.csb.modules.model.Invoice
 * @generated
 */
public abstract class InvoiceBaseImpl extends InvoiceModelImpl
    implements Invoice {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a invoice model instance should use the {@link Invoice} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            InvoiceLocalServiceUtil.addInvoice(this);
        } else {
            InvoiceLocalServiceUtil.updateInvoice(this);
        }
    }
}
