package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Payment;
import com.arman.csb.modules.service.PaymentLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Payment service. Represents a row in the &quot;CSBModules_Payment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PaymentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PaymentImpl
 * @see com.arman.csb.modules.model.Payment
 * @generated
 */
public abstract class PaymentBaseImpl extends PaymentModelImpl
    implements Payment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a payment model instance should use the {@link Payment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PaymentLocalServiceUtil.addPayment(this);
        } else {
            PaymentLocalServiceUtil.updatePayment(this);
        }
    }
}
