package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Product;
import com.arman.csb.modules.service.ProductLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Product service. Represents a row in the &quot;CSBModules_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductImpl
 * @see com.arman.csb.modules.model.Product
 * @generated
 */
public abstract class ProductBaseImpl extends ProductModelImpl
    implements Product {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a product model instance should use the {@link Product} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ProductLocalServiceUtil.addProduct(this);
        } else {
            ProductLocalServiceUtil.updateProduct(this);
        }
    }
}
