package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.Score;
import com.arman.csb.modules.service.ScoreLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Score service. Represents a row in the &quot;CSBModules_Score&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScoreImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScoreImpl
 * @see com.arman.csb.modules.model.Score
 * @generated
 */
public abstract class ScoreBaseImpl extends ScoreModelImpl implements Score {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a score model instance should use the {@link Score} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ScoreLocalServiceUtil.addScore(this);
        } else {
            ScoreLocalServiceUtil.updateScore(this);
        }
    }
}
