package com.arman.csb.modules.model.impl;

import com.arman.csb.modules.model.UserActivity;
import com.arman.csb.modules.service.UserActivityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the UserActivity service. Represents a row in the &quot;CSBModules_UserActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserActivityImpl
 * @see com.arman.csb.modules.model.UserActivity
 * @generated
 */
public abstract class UserActivityBaseImpl extends UserActivityModelImpl
    implements UserActivity {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a user activity model instance should use the {@link UserActivity} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UserActivityLocalServiceUtil.addUserActivity(this);
        } else {
            UserActivityLocalServiceUtil.updateUserActivity(this);
        }
    }
}
